# Generated by Django 5.1.4 on 2025-01-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_stocktrade_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktrade',
            old_name='publisher',
            new_name='trader',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_publisher',
            new_name='is_trader',
        ),
    ]
